### ISSUE TITLE
Enhancement Request : dot color : Or a pointer as to how to implement

### ISSUE THREAD

**Issue by wm-j-ray** [wannabegeek/PageViewController#2]
Tom,

This control works flawlessly and I'm trying to figure out how to implement changing the dot color for selected and non-selected states.

Can you give me a pointer as to how to implement?

Thanx in Advance

**Comment by wannabegeek** [comment]
I don't think this is possible, there is nothing in the UIPageControl API to change the colour or apply a tint. As far as I can see, the only way of doing this is to implement your own UIPageControl (or subclass it and implement - (void)drawRect:(CGRect)rect

Hope that helps.

Thanks,
Tom

**Comment by wm-j-ray** [comment]
I found a PageControl h/m and tried to plug it into StoryBoard in IB but couldn't get IB to take it. 

I'm not sure how to do it programmatically.

**Comment by wm-j-ray** [comment]
Well, I got it to work by subclassing UIPageControl, eliminating the existing PageControl from the storyboard and creating it programatically using this implementation of PageControl : http://stackoverflow.com/questions/2942636/how-i-change-the-color-of-pagination-dots-of-uipagecontrol

A little 'hackie', but it works.  Thanx for the help

**Comment by wm-j-ray** [comment]
I want to load a view controller other than self.childViewControllers objectAtIndex:0.

I'm struggling with how to do it.  Can you get me started?
Thanx in Advance
